--- #oznacava yml file

name: Checks

on: [push] #trigger koji se aktivira na push

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # vise razlicitih runnera,  operacijski sustav na kojemu pokrecemo job, za python najbolje u ubuntu --  jer je lagan
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker- compose run --rm app sh -c "flake8"


